[2023-10-29T18:47:53.746+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:47:53.747+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:47:53.749+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:47:53.749+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:47:54.112+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:47:53.960+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 2, in <module>
    from ariflow.operators.python import PythonOperator
ModuleNotFoundError: No module named 'ariflow'
[2023-10-29T18:47:54.112+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:47:54.360+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.622 seconds
[2023-10-29T18:48:24.640+0000] {processor.py:157} INFO - Started process (PID=181) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:48:24.678+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:48:24.681+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:48:24.680+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:48:25.102+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:48:24.906+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 2, in <module>
    from ariflow.operators.python import PythonOperator
ModuleNotFoundError: No module named 'ariflow'
[2023-10-29T18:48:25.103+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:48:28.077+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 3.447 seconds
[2023-10-29T18:48:58.284+0000] {processor.py:157} INFO - Started process (PID=193) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:48:58.513+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:48:58.517+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:48:58.516+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:48:58.528+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:48:58.525+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 2, in <module>
    from ariflow.operators.python import PythonOperator
ModuleNotFoundError: No module named 'ariflow'
[2023-10-29T18:48:58.529+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:48:58.761+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.481 seconds
[2023-10-29T18:49:29.132+0000] {processor.py:157} INFO - Started process (PID=205) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:49:29.173+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:49:29.175+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:49:29.174+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:49:29.249+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:49:29.224+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 2, in <module>
    from ariflow.operators.python import PythonOperator
ModuleNotFoundError: No module named 'ariflow'
[2023-10-29T18:49:29.250+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:49:29.642+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.520 seconds
[2023-10-29T18:49:57.471+0000] {processor.py:157} INFO - Started process (PID=217) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:49:57.472+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:49:57.473+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:49:57.473+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:49:57.660+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:49:57.608+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    python_callable=start_streaming
NameError: name 'start_streaming' is not defined
[2023-10-29T18:49:57.662+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:49:57.849+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.381 seconds
[2023-10-29T18:50:28.082+0000] {processor.py:157} INFO - Started process (PID=229) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:50:28.108+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:50:28.109+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:50:28.109+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:50:28.159+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:50:28.148+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    python_callable=start_streaming
NameError: name 'start_streaming' is not defined
[2023-10-29T18:50:28.160+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:50:28.240+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.163 seconds
[2023-10-29T18:50:58.266+0000] {processor.py:157} INFO - Started process (PID=241) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:50:58.266+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:50:58.267+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:50:58.267+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:50:58.397+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:50:58.396+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    python_callable=start_streaming
NameError: name 'start_streaming' is not defined
[2023-10-29T18:50:58.397+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:50:58.462+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.200 seconds
[2023-10-29T18:51:18.587+0000] {processor.py:157} INFO - Started process (PID=253) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:51:18.722+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:51:18.724+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:51:18.723+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:51:18.733+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:51:18.732+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    python_callable=start_streaming
NameError: name 'start_streaming' is not defined
[2023-10-29T18:51:18.734+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:51:18.765+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.189 seconds
[2023-10-29T18:51:38.866+0000] {processor.py:157} INFO - Started process (PID=258) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:51:38.867+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:51:38.867+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:51:38.867+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:51:38.955+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:51:38.951+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from script import start_streaming
  File "/opt/airflow/dags/script.py", line 1, in <module>
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2023-10-29T18:51:38.956+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:51:39.008+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.144 seconds
[2023-10-29T18:52:09.119+0000] {processor.py:157} INFO - Started process (PID=270) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:52:09.129+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:52:09.131+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:52:09.130+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:52:09.218+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:52:09.188+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T18:52:09.220+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:52:09.334+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.217 seconds
[2023-10-29T18:52:16.253+0000] {processor.py:157} INFO - Started process (PID=275) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:52:16.255+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:52:16.256+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:52:16.255+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:52:16.262+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:52:16.261+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T18:52:16.262+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:52:16.290+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.041 seconds
[2023-10-29T18:52:34.448+0000] {processor.py:157} INFO - Started process (PID=287) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:52:34.448+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:52:34.449+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:52:34.449+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:52:34.453+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:52:34.452+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from scripts.script import start_streaming
ModuleNotFoundError: No module named 'scripts'
[2023-10-29T18:52:34.453+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:52:34.548+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.107 seconds
[2023-10-29T18:53:05.197+0000] {processor.py:157} INFO - Started process (PID=299) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:53:05.282+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:53:05.287+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:53:05.286+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:53:05.297+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:53:05.295+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from scripts.script import start_streaming
ModuleNotFoundError: No module named 'scripts'
[2023-10-29T18:53:05.297+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:53:05.492+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.298 seconds
[2023-10-29T18:53:35.713+0000] {processor.py:157} INFO - Started process (PID=311) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:53:35.715+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:53:35.717+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:53:35.717+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:53:35.724+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:53:35.723+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from scripts.script import start_streaming
ModuleNotFoundError: No module named 'scripts'
[2023-10-29T18:53:35.725+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:53:35.786+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.086 seconds
[2023-10-29T18:54:05.923+0000] {processor.py:157} INFO - Started process (PID=323) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:54:05.944+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:54:05.947+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:54:05.946+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:54:05.957+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:54:05.955+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from scripts.script import start_streaming
ModuleNotFoundError: No module named 'scripts'
[2023-10-29T18:54:05.959+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:54:05.987+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.072 seconds
[2023-10-29T18:54:35.121+0000] {processor.py:157} INFO - Started process (PID=335) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:54:35.122+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:54:35.123+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:54:35.122+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:54:35.411+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:54:35.408+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T18:54:35.412+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:54:35.477+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.365 seconds
[2023-10-29T18:55:05.786+0000] {processor.py:157} INFO - Started process (PID=347) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:55:05.837+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:55:05.890+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:55:05.840+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:55:06.366+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:55:06.330+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T18:55:06.367+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T18:55:07.205+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 1.517 seconds
[2023-10-29T18:56:51.326+0000] {processor.py:157} INFO - Started process (PID=352) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:57:03.482+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:57:14.227+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:57:13.198+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:58:07.036+0000] {processor.py:157} INFO - Started process (PID=355) to work on /opt/airflow/dags/dag.py
[2023-10-29T18:58:08.645+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T18:58:08.648+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:58:08.647+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T18:58:32.505+0000] {logging_mixin.py:151} INFO - [2023-10-29T18:58:21.937+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T18:58:33.433+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:01:30.684+0000] {processor.py:157} INFO - Started process (PID=358) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:01:42.804+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:01:53.086+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:01:53.086+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:02:59.741+0000] {processor.py:157} INFO - Started process (PID=361) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:03:02.735+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:03:03.568+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:03:02.736+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:03:18.698+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:03:17.436+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:03:19.488+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:04:32.779+0000] {processor.py:157} INFO - Started process (PID=370) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:04:35.612+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:04:35.964+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:04:35.614+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:04:47.501+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:04:42.721+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:04:47.503+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:05:44.324+0000] {processor.py:157} INFO - Started process (PID=373) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:05:47.248+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:05:48.762+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:05:47.250+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:06:09.697+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:06:03.238+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:06:10.001+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:11:49.855+0000] {processor.py:157} INFO - Started process (PID=182) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:11:49.980+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:11:49.981+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:11:49.980+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:11:50.101+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:11:50.031+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:11:50.101+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:11:50.195+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.341 seconds
[2023-10-29T19:12:20.379+0000] {processor.py:157} INFO - Started process (PID=194) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:12:20.407+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:12:20.408+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:12:20.408+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:12:20.411+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:12:20.410+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 8, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:12:20.411+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:12:20.462+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.086 seconds
[2023-10-29T19:18:43.199+0000] {processor.py:157} INFO - Started process (PID=175) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:18:43.476+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:18:43.478+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:18:43.477+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:18:44.105+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:18:43.994+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from .scripts.script import start_streaming
ImportError: attempted relative import with no known parent package
[2023-10-29T19:18:44.105+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:18:44.195+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 1.003 seconds
[2023-10-29T19:19:14.373+0000] {processor.py:157} INFO - Started process (PID=187) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:19:14.576+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:19:14.580+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:19:14.579+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:19:14.740+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:19:14.693+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from .scripts.script import start_streaming
ImportError: attempted relative import with no known parent package
[2023-10-29T19:19:14.741+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:19:15.236+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.866 seconds
[2023-10-29T19:22:03.846+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:22:04.015+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:22:04.015+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:22:04.015+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:22:04.082+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:22:04.017+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from .scripts.script import start_streaming
ImportError: attempted relative import with no known parent package
[2023-10-29T19:22:04.160+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:22:04.215+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.372 seconds
[2023-10-29T19:22:34.825+0000] {processor.py:157} INFO - Started process (PID=181) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:22:34.873+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:22:34.874+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:22:34.874+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:22:35.128+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:22:34.974+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from .scripts.script import start_streaming
ImportError: attempted relative import with no known parent package
[2023-10-29T19:22:35.129+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:22:36.951+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 2.129 seconds
[2023-10-29T19:23:07.180+0000] {processor.py:157} INFO - Started process (PID=193) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:23:07.244+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:23:07.247+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:23:07.246+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:23:07.256+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:23:07.253+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from .scripts.script import start_streaming
ImportError: attempted relative import with no known parent package
[2023-10-29T19:23:07.257+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:23:07.341+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.172 seconds
[2023-10-29T19:23:37.416+0000] {processor.py:157} INFO - Started process (PID=205) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:23:37.417+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:23:37.419+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:23:37.418+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:23:37.507+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:23:37.455+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from .scripts.script import start_streaming
ImportError: attempted relative import with no known parent package
[2023-10-29T19:23:37.508+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:23:37.614+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.206 seconds
[2023-10-29T19:24:07.742+0000] {processor.py:157} INFO - Started process (PID=216) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:24:07.770+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:24:07.772+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:24:07.771+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:24:07.781+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:24:07.778+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from .scripts.script import start_streaming
ImportError: attempted relative import with no known parent package
[2023-10-29T19:24:07.782+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:24:08.039+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.300 seconds
[2023-10-29T19:24:08.857+0000] {processor.py:157} INFO - Started process (PID=221) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:24:08.859+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:24:08.860+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:24:08.860+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:24:08.865+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:24:08.864+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from .scripts import script
ImportError: attempted relative import with no known parent package
[2023-10-29T19:24:08.866+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:24:08.998+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.149 seconds
[2023-10-29T19:24:13.053+0000] {processor.py:157} INFO - Started process (PID=226) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:24:13.054+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:24:13.054+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:24:13.054+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:24:13.057+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:24:13.056+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from .scripts import script
ImportError: attempted relative import with no known parent package
[2023-10-29T19:24:13.057+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:24:13.101+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.051 seconds
[2023-10-29T19:24:36.288+0000] {processor.py:157} INFO - Started process (PID=238) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:24:36.290+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:24:36.293+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:24:36.291+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:24:36.331+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:24:36.328+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from scripts import script
ModuleNotFoundError: No module named 'scripts'
[2023-10-29T19:24:36.332+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:24:36.385+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.135 seconds
[2023-10-29T19:24:45.364+0000] {processor.py:157} INFO - Started process (PID=243) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:24:45.365+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:24:45.366+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:24:45.366+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:24:45.372+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:24:45.370+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from .scripts import script
ImportError: attempted relative import with no known parent package
[2023-10-29T19:24:45.372+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:24:45.547+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.189 seconds
[2023-10-29T19:25:15.687+0000] {processor.py:157} INFO - Started process (PID=254) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:25:15.772+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:25:15.772+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:25:15.772+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:25:15.775+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:25:15.774+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from .scripts import script
ImportError: attempted relative import with no known parent package
[2023-10-29T19:25:15.775+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:25:15.832+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.151 seconds
[2023-10-29T19:25:45.950+0000] {processor.py:157} INFO - Started process (PID=267) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:25:46.322+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:25:46.323+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:25:46.323+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:25:46.590+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:25:46.472+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from .scripts import script
ImportError: attempted relative import with no known parent package
[2023-10-29T19:25:46.591+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:25:46.714+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.772 seconds
[2023-10-29T19:39:02.492+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:39:03.044+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:39:03.046+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:39:03.045+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:39:04.354+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:39:04.214+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from scripts.script import your_function_name
ModuleNotFoundError: No module named 'scripts'
[2023-10-29T19:39:04.355+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:39:06.422+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 3.932 seconds
[2023-10-29T19:39:36.866+0000] {processor.py:157} INFO - Started process (PID=181) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:39:36.968+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:39:36.969+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:39:36.968+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:39:37.022+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:39:36.998+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from scripts.script import your_function_name
ModuleNotFoundError: No module named 'scripts'
[2023-10-29T19:39:37.023+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:39:37.218+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.361 seconds
[2023-10-29T19:40:07.490+0000] {processor.py:157} INFO - Started process (PID=193) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:40:08.085+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:40:08.089+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:40:08.088+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:40:09.523+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:40:08.803+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from scripts.script import your_function_name
ModuleNotFoundError: No module named 'scripts'
[2023-10-29T19:40:09.525+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:40:11.106+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 3.622 seconds
[2023-10-29T19:40:34.294+0000] {processor.py:157} INFO - Started process (PID=205) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:40:34.545+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:40:34.548+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:40:34.547+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:40:34.970+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:40:34.904+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from scripts.script import start_streaming
ModuleNotFoundError: No module named 'scripts'
[2023-10-29T19:40:34.971+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:40:35.090+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.805 seconds
[2023-10-29T19:41:05.734+0000] {processor.py:157} INFO - Started process (PID=216) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:41:06.205+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:41:06.207+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:41:06.206+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:41:06.934+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:41:06.641+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from scripts.script import start_streaming
ModuleNotFoundError: No module named 'scripts'
[2023-10-29T19:41:06.934+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:41:07.594+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 1.869 seconds
[2023-10-29T19:41:37.829+0000] {processor.py:157} INFO - Started process (PID=222) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:41:37.840+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:41:37.841+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:41:37.841+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:41:37.844+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:41:37.843+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from scripts.script import start_streaming
ModuleNotFoundError: No module named 'scripts'
[2023-10-29T19:41:37.844+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:41:37.865+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.040 seconds
[2023-10-29T19:41:53.973+0000] {processor.py:157} INFO - Started process (PID=234) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:41:53.978+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:41:53.979+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:41:53.979+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:41:53.985+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:41:53.984+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from .scripts.script import start_streaming
ImportError: attempted relative import with no known parent package
[2023-10-29T19:41:53.986+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:41:54.006+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.044 seconds
[2023-10-29T19:42:27.758+0000] {processor.py:157} INFO - Started process (PID=246) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:42:28.229+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:42:28.353+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:42:28.231+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:42:29.201+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:42:28.808+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from .scripts.script import start_streaming
ImportError: attempted relative import with no known parent package
[2023-10-29T19:42:29.203+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:42:32.737+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 5.491 seconds
[2023-10-29T19:43:03.324+0000] {processor.py:157} INFO - Started process (PID=258) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:43:03.536+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:43:03.539+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:43:03.538+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:43:03.823+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:43:03.820+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from .scripts.script import start_streaming
ImportError: attempted relative import with no known parent package
[2023-10-29T19:43:03.824+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:43:07.525+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 4.207 seconds
[2023-10-29T19:43:38.285+0000] {processor.py:157} INFO - Started process (PID=270) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:43:38.568+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:43:38.570+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:43:38.569+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:43:38.729+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:43:38.633+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from .scripts.script import start_streaming
ImportError: attempted relative import with no known parent package
[2023-10-29T19:43:38.731+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:43:39.377+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 1.102 seconds
[2023-10-29T19:44:10.442+0000] {processor.py:157} INFO - Started process (PID=282) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:44:10.558+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:44:10.561+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:44:10.560+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:44:10.694+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:44:10.568+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from .scripts.script import start_streaming
ImportError: attempted relative import with no known parent package
[2023-10-29T19:44:10.695+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:44:10.781+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.343 seconds
[2023-10-29T19:44:40.994+0000] {processor.py:157} INFO - Started process (PID=294) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:44:41.039+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:44:41.041+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:44:41.041+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:44:41.050+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:44:41.047+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from .scripts.script import start_streaming
ImportError: attempted relative import with no known parent package
[2023-10-29T19:44:41.051+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:44:41.124+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.141 seconds
[2023-10-29T19:45:16.142+0000] {processor.py:157} INFO - Started process (PID=306) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:45:18.003+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:45:18.248+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:45:18.005+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:45:20.439+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:45:19.338+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from .scripts.script import start_streaming
ImportError: attempted relative import with no known parent package
[2023-10-29T19:45:20.440+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:45:32.797+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 17.478 seconds
[2023-10-29T19:47:46.549+0000] {processor.py:157} INFO - Started process (PID=317) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:47:47.838+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:47:47.942+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:47:47.840+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:47:51.760+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:47:50.675+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from .scripts.script import start_streaming
ImportError: attempted relative import with no known parent package
[2023-10-29T19:47:51.760+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:48:01.223+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 15.210 seconds
[2023-10-29T19:48:08.301+0000] {processor.py:157} INFO - Started process (PID=330) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:48:08.457+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:48:08.459+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:48:08.459+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:48:08.758+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:48:08.755+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:48:08.760+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:48:09.122+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.829 seconds
[2023-10-29T19:48:13.194+0000] {processor.py:157} INFO - Started process (PID=335) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:48:13.195+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:48:13.195+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:48:13.195+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:48:13.199+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:48:13.198+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:48:13.200+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:48:13.305+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.115 seconds
[2023-10-29T19:48:15.226+0000] {processor.py:157} INFO - Started process (PID=340) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:48:15.227+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:48:15.228+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:48:15.227+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:48:15.231+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:48:15.231+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:48:15.232+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:48:15.297+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.075 seconds
[2023-10-29T19:48:45.442+0000] {processor.py:157} INFO - Started process (PID=352) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:48:45.585+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:48:45.587+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:48:45.586+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:48:45.598+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:48:45.595+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:48:45.599+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:48:45.830+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.399 seconds
[2023-10-29T19:49:16.027+0000] {processor.py:157} INFO - Started process (PID=364) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:49:16.079+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:49:16.082+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:49:16.081+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:49:16.092+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:49:16.089+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:49:16.093+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:49:16.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.289 seconds
[2023-10-29T19:49:46.502+0000] {processor.py:157} INFO - Started process (PID=376) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:49:46.508+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:49:46.509+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:49:46.508+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:49:46.512+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:49:46.511+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:49:46.512+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:49:46.537+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.037 seconds
[2023-10-29T19:50:16.694+0000] {processor.py:157} INFO - Started process (PID=388) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:50:16.707+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:50:16.709+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:50:16.708+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:50:16.788+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:50:16.759+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:50:16.789+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:50:16.879+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.190 seconds
[2023-10-29T19:50:47.354+0000] {processor.py:157} INFO - Started process (PID=400) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:50:47.356+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:50:47.393+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:50:47.358+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:50:48.221+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:50:48.124+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 16, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:50:48.222+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:50:48.873+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 1.641 seconds
[2023-10-29T19:50:51.950+0000] {processor.py:157} INFO - Started process (PID=405) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:50:52.040+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:50:52.043+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:50:52.042+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:50:52.054+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:50:52.051+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 18, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:50:52.055+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:50:52.181+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.239 seconds
[2023-10-29T19:50:58.254+0000] {processor.py:157} INFO - Started process (PID=410) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:50:58.291+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:50:58.292+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:50:58.292+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:50:58.295+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:50:58.294+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 17, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:50:58.295+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:50:58.336+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.084 seconds
[2023-10-29T19:51:32.490+0000] {processor.py:157} INFO - Started process (PID=415) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:51:33.633+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:51:34.442+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:51:33.635+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:51:40.025+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:51:36.519+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 17, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:51:40.026+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:51:51.747+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 19.269 seconds
[2023-10-29T19:52:22.450+0000] {processor.py:157} INFO - Started process (PID=426) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:52:22.732+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:52:22.736+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:52:22.734+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:52:23.172+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:52:23.063+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 17, in <module>
    from script import start_streaming
ModuleNotFoundError: No module named 'script'
[2023-10-29T19:52:23.174+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:52:24.475+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 2.030 seconds
[2023-10-29T19:52:44.649+0000] {processor.py:157} INFO - Started process (PID=438) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:52:44.651+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:52:44.654+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:52:44.653+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:52:44.794+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:52:44.768+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from scripts.script import start_streaming
  File "/opt/airflow/dags/scripts/script.py", line 1, in <module>
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2023-10-29T19:52:44.795+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:52:45.212+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.574 seconds
[2023-10-29T19:53:15.444+0000] {processor.py:157} INFO - Started process (PID=450) to work on /opt/airflow/dags/dag.py
[2023-10-29T19:53:15.855+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T19:53:15.858+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:53:15.857+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T19:53:17.522+0000] {logging_mixin.py:151} INFO - [2023-10-29T19:53:17.011+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 5, in <module>
    from scripts.script import start_streaming
  File "/opt/airflow/dags/scripts/script.py", line 1, in <module>
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2023-10-29T19:53:17.524+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2023-10-29T19:53:18.963+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 3.528 seconds
[2023-10-29T20:15:33.989+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/dag.py
[2023-10-29T20:15:34.068+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T20:15:34.070+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:15:34.070+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T20:15:36.958+0000] {processor.py:839} INFO - DAG(s) dict_keys(['random_names']) retrieved from /opt/airflow/dags/dag.py
[2023-10-29T20:15:39.548+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:15:39.547+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-10-29T20:15:39.815+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:15:39.815+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-10-29T20:15:40.152+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:15:40.151+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-10-29T20:15:40.153+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:15:40.153+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:random_names' as access control is unset.
[2023-10-29T20:15:40.154+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:15:40.153+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2023-10-29T20:15:40.244+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:15:40.244+0000] {dag.py:2937} INFO - Creating ORM DAG for random_names
[2023-10-29T20:15:40.281+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:15:40.281+0000] {dag.py:3696} INFO - Setting next_dagrun for random_names to 2023-10-29T20:10:00+00:00, run_after=2023-10-29T20:15:00+00:00
[2023-10-29T20:15:40.423+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 6.436 seconds
[2023-10-29T20:16:10.643+0000] {processor.py:157} INFO - Started process (PID=181) to work on /opt/airflow/dags/dag.py
[2023-10-29T20:16:10.779+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T20:16:10.781+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:16:10.780+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T20:16:12.153+0000] {processor.py:839} INFO - DAG(s) dict_keys(['random_names']) retrieved from /opt/airflow/dags/dag.py
[2023-10-29T20:16:12.715+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:16:12.715+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2023-10-29T20:16:12.759+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:16:12.759+0000] {dag.py:3696} INFO - Setting next_dagrun for random_names to 2023-10-29T20:10:00+00:00, run_after=2023-10-29T20:15:00+00:00
[2023-10-29T20:16:12.815+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 2.182 seconds
[2023-10-29T20:16:43.468+0000] {processor.py:157} INFO - Started process (PID=193) to work on /opt/airflow/dags/dag.py
[2023-10-29T20:16:44.077+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T20:16:44.079+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:16:44.078+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T20:16:57.673+0000] {processor.py:839} INFO - DAG(s) dict_keys(['random_names']) retrieved from /opt/airflow/dags/dag.py
[2023-10-29T20:17:00.403+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:17:00.402+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2023-10-29T20:17:00.444+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:17:00.444+0000] {dag.py:3696} INFO - Setting next_dagrun for random_names to 2023-10-29T20:10:00+00:00, run_after=2023-10-29T20:15:00+00:00
[2023-10-29T20:17:00.955+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 17.497 seconds
[2023-10-29T20:17:31.513+0000] {processor.py:157} INFO - Started process (PID=212) to work on /opt/airflow/dags/dag.py
[2023-10-29T20:17:31.606+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T20:17:31.609+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:17:31.608+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T20:17:31.762+0000] {processor.py:839} INFO - DAG(s) dict_keys(['random_names']) retrieved from /opt/airflow/dags/dag.py
[2023-10-29T20:17:31.779+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:17:31.779+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2023-10-29T20:17:31.794+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:17:31.794+0000] {dag.py:3696} INFO - Setting next_dagrun for random_names to 2023-10-29T20:10:00+00:00, run_after=2023-10-29T20:15:00+00:00
[2023-10-29T20:17:31.812+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.304 seconds
[2023-10-29T20:18:02.017+0000] {processor.py:157} INFO - Started process (PID=225) to work on /opt/airflow/dags/dag.py
[2023-10-29T20:18:02.019+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T20:18:02.021+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:18:02.020+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T20:18:03.812+0000] {processor.py:839} INFO - DAG(s) dict_keys(['random_names']) retrieved from /opt/airflow/dags/dag.py
[2023-10-29T20:18:05.440+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:18:05.440+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2023-10-29T20:18:05.467+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:18:05.467+0000] {dag.py:3696} INFO - Setting next_dagrun for random_names to 2023-10-29T20:15:00+00:00, run_after=2023-10-29T20:20:00+00:00
[2023-10-29T20:18:05.663+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 3.655 seconds
[2023-10-29T20:18:36.207+0000] {processor.py:157} INFO - Started process (PID=240) to work on /opt/airflow/dags/dag.py
[2023-10-29T20:18:36.208+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T20:18:36.209+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:18:36.209+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T20:18:36.338+0000] {processor.py:839} INFO - DAG(s) dict_keys(['random_names']) retrieved from /opt/airflow/dags/dag.py
[2023-10-29T20:18:36.395+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:18:36.395+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2023-10-29T20:18:36.413+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:18:36.413+0000] {dag.py:3696} INFO - Setting next_dagrun for random_names to 2023-10-29T20:15:00+00:00, run_after=2023-10-29T20:20:00+00:00
[2023-10-29T20:18:36.448+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.248 seconds
[2023-10-29T20:19:06.533+0000] {processor.py:157} INFO - Started process (PID=254) to work on /opt/airflow/dags/dag.py
[2023-10-29T20:19:06.535+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T20:19:06.536+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:19:06.536+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T20:19:07.220+0000] {processor.py:839} INFO - DAG(s) dict_keys(['random_names']) retrieved from /opt/airflow/dags/dag.py
[2023-10-29T20:19:07.787+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:19:07.786+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2023-10-29T20:19:07.823+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:19:07.822+0000] {dag.py:3696} INFO - Setting next_dagrun for random_names to 2023-10-29T20:15:00+00:00, run_after=2023-10-29T20:20:00+00:00
[2023-10-29T20:19:07.962+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 1.436 seconds
[2023-10-29T20:19:38.139+0000] {processor.py:157} INFO - Started process (PID=268) to work on /opt/airflow/dags/dag.py
[2023-10-29T20:19:38.257+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T20:19:38.260+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:19:38.259+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T20:19:38.443+0000] {processor.py:839} INFO - DAG(s) dict_keys(['random_names']) retrieved from /opt/airflow/dags/dag.py
[2023-10-29T20:19:38.622+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:19:38.621+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2023-10-29T20:19:38.649+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:19:38.648+0000] {dag.py:3696} INFO - Setting next_dagrun for random_names to 2023-10-29T20:15:00+00:00, run_after=2023-10-29T20:20:00+00:00
[2023-10-29T20:19:38.694+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.559 seconds
[2023-10-29T20:20:08.960+0000] {processor.py:157} INFO - Started process (PID=281) to work on /opt/airflow/dags/dag.py
[2023-10-29T20:20:09.156+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T20:20:09.157+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:20:09.157+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T20:20:12.614+0000] {processor.py:839} INFO - DAG(s) dict_keys(['random_names']) retrieved from /opt/airflow/dags/dag.py
[2023-10-29T20:20:14.365+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:20:14.365+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2023-10-29T20:20:14.592+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:20:14.592+0000] {dag.py:3696} INFO - Setting next_dagrun for random_names to 2023-10-29T20:20:00+00:00, run_after=2023-10-29T20:25:00+00:00
[2023-10-29T20:20:14.654+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 5.697 seconds
[2023-10-29T20:20:44.801+0000] {processor.py:157} INFO - Started process (PID=294) to work on /opt/airflow/dags/dag.py
[2023-10-29T20:20:44.818+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2023-10-29T20:20:44.821+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:20:44.820+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2023-10-29T20:20:44.928+0000] {processor.py:839} INFO - DAG(s) dict_keys(['random_names']) retrieved from /opt/airflow/dags/dag.py
[2023-10-29T20:20:44.948+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:20:44.947+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2023-10-29T20:20:44.967+0000] {logging_mixin.py:151} INFO - [2023-10-29T20:20:44.966+0000] {dag.py:3696} INFO - Setting next_dagrun for random_names to 2023-10-29T20:20:00+00:00, run_after=2023-10-29T20:25:00+00:00
[2023-10-29T20:20:45.028+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag.py took 0.238 seconds
