[2023-10-31T20:39:14.254+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_names.streaming_to_kafka manual__2023-10-31T20:38:48.963802+00:00 [queued]>
[2023-10-31T20:39:14.265+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_names.streaming_to_kafka manual__2023-10-31T20:38:48.963802+00:00 [queued]>
[2023-10-31T20:39:14.265+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-31T20:39:14.476+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): streaming_to_kafka> on 2023-10-31 20:38:48.963802+00:00
[2023-10-31T20:39:14.485+0000] {standard_task_runner.py:57} INFO - Started process 232 to run task
[2023-10-31T20:39:14.490+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'random_names', 'streaming_to_kafka', 'manual__2023-10-31T20:38:48.963802+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp19bhp8rn']
[2023-10-31T20:39:14.495+0000] {standard_task_runner.py:85} INFO - Job 64: Subtask streaming_to_kafka
[2023-10-31T20:39:15.548+0000] {task_command.py:415} INFO - Running <TaskInstance: random_names.streaming_to_kafka manual__2023-10-31T20:38:48.963802+00:00 [running]> on host 5306fede0ec7
[2023-10-31T20:39:16.221+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='random_names' AIRFLOW_CTX_TASK_ID='streaming_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2023-10-31T20:38:48.963802+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-31T20:38:48.963802+00:00'
[2023-10-31T20:39:20.006+0000] {logging_mixin.py:151} INFO - {'full name': 'Mrs Vilma Latt', 'gender': 'female', 'location': 'Rotuaari 4492', 'city': 'Sysm√§', 'country': 'Finland', 'postcode': 87717, 'latitude': '-27.4335', 'longtitude': '88.3137', 'email': 'vilma.latt@example.com'}
[2023-10-31T20:39:20.014+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.21.0.6', 9092)]>: connecting to kafka:9092 [('172.21.0.6', 9092) IPv4]
[2023-10-31T20:39:20.016+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-10-31T20:39:20.017+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.21.0.6', 9092)]>: Connection complete.
[2023-10-31T20:39:22.123+0000] {conn.py:1055} WARNING - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.21.0.6', 9092)]> timed out after 1995.5039024353027 ms. Closing connection.
[2023-10-31T20:39:22.124+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.21.0.6', 9092)]>: Closing connection. [Error 7] RequestTimedOutError: Request timed out after 1995.5039024353027 ms
[2023-10-31T20:39:22.125+0000] {conn.py:1293} INFO - Broker is not v(0, 10) -- it did not recognize ApiVersionRequest_v0
[2023-10-31T20:39:22.126+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/script.py", line 50, in start_streaming
    producer = get_kafka_producer()
  File "/opt/airflow/dags/scripts/script.py", line 31, in get_kafka_producer
    producer = KafkaProducer(
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2023-10-31T20:39:23.352+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=random_names, task_id=streaming_to_kafka, execution_date=20231031T203848, start_date=20231031T203914, end_date=20231031T203923
[2023-10-31T20:39:27.929+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 64 for task streaming_to_kafka (NoBrokersAvailable; 232)
[2023-10-31T20:39:28.056+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-31T20:39:29.316+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
